# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 14:45
from __future__ import unicode_literals

import core.models
import django.core.serializers.json
from django.db import migrations, models
import django_pgjsonb.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='custom_data',
            field=django_pgjsonb.fields.JSONField(db_index=True, db_index_options=[{}], decode_kwargs={}, default=core.models.json_default, encode_kwargs={'cls': django.core.serializers.json.DjangoJSONEncoder}),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
