# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_child'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.IntegerField(choices=[(100, 'Ready By'), (200, 'Chore'), (300, 'Curfew')])),
                ('at_time', models.TimeField()),
                ('on_mon', models.BooleanField(default=False)),
                ('on_tue', models.BooleanField(default=False)),
                ('on_wed', models.BooleanField(default=False)),
                ('on_thu', models.BooleanField(default=False)),
                ('on_fri', models.BooleanField(default=False)),
                ('on_sat', models.BooleanField(default=False)),
                ('on_sun', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='core.Child')),
            ],
        ),
    ]
