# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_appuser_time_offset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='at_time',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='on_fri',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='on_mon',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='on_sat',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='on_sun',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='on_thu',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='on_tue',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='on_wed',
        ),
        migrations.AddField(
            model_name='reminder',
            name='for_desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='one_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='repeat_at_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='repeat_days',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
