# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170630_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('status', models.IntegerField(choices=[(100, 'Scheduled 1st Request'), (200, 'Sent 1st Request'), (300, 'Scheduled 2nd Request'), (400, 'Sent 2nd Request'), (500, 'Awaiting Response'), (600, 'Incomplete'), (700, 'Complete')])),
                ('scheduled_time', models.DateTimeField()),
                ('request_count', models.IntegerField(default=0)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.Reminder')),
            ],
        ),
    ]
