# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='event_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
