# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_action_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='phone_number',
            field=models.CharField(default='default', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
