# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170701_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='excuse',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.IntegerField(choices=[(100, 'Scheduled 1st Request'), (300, 'Scheduled 2nd Request'), (500, 'Awaiting Response'), (600, 'Incomplete'), (700, 'Complete')]),
        ),
    ]
